// ─────────────────────────────────────
// Enums - matching Prisma schema exactly
// ─────────────────────────────────────

export enum UserRole {
  PARTICIPANT = 'PARTICIPANT',
  BUSINESS_ADMIN = 'BUSINESS_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum OrgStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
}

export enum OrgMemberRole {
  OWNER = 'OWNER',
  MEMBER = 'MEMBER',
}

export enum BountyStatus {
  DRAFT = 'DRAFT',
  LIVE = 'LIVE',
  PAUSED = 'PAUSED',
  CLOSED = 'CLOSED',
}

export enum RewardType {
  CASH = 'CASH',
  PRODUCT = 'PRODUCT',
  SERVICE = 'SERVICE',
  OTHER = 'OTHER',
}

export enum SubmissionStatus {
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW = 'IN_REVIEW',
  NEEDS_MORE_INFO = 'NEEDS_MORE_INFO',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PayoutStatus {
  NOT_PAID = 'NOT_PAID',
  PENDING = 'PENDING',
  PAID = 'PAID',
}

export enum SocialChannel {
  INSTAGRAM = 'INSTAGRAM',
  FACEBOOK = 'FACEBOOK',
  TIKTOK = 'TIKTOK',
}

export enum PostFormat {
  STORY = 'STORY',
  REEL = 'REEL',
  FEED_POST = 'FEED_POST',
  VIDEO_POST = 'VIDEO_POST',
}

export enum PostVisibilityRule {
  MUST_NOT_REMOVE = 'MUST_NOT_REMOVE',
  MINIMUM_DURATION = 'MINIMUM_DURATION',
}

export enum DurationUnit {
  HOURS = 'HOURS',
  DAYS = 'DAYS',
  WEEKS = 'WEEKS',
}

export enum Currency {
  ZAR = 'ZAR',
  USD = 'USD',
  GBP = 'GBP',
  EUR = 'EUR',
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PENDING = 'PENDING',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
}

export enum PayoutMethod {
  PAYPAL = 'PAYPAL',
  BANK_TRANSFER = 'BANK_TRANSFER',
  E_WALLET = 'E_WALLET',
}

// ─── Wallet Enums ────────────────────

export enum WalletTxType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  HOLD = 'HOLD',
  RELEASE = 'RELEASE',
  CORRECTION = 'CORRECTION',
}

export enum WithdrawalStatus {
  REQUESTED = 'REQUESTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

// ─── Dispute Enums ───────────────────

export enum DisputeStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  AWAITING_RESPONSE = 'AWAITING_RESPONSE',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum DisputeCategory {
  NON_PAYMENT = 'NON_PAYMENT',
  POST_QUALITY = 'POST_QUALITY',
  POST_NON_COMPLIANCE = 'POST_NON_COMPLIANCE',
}

export enum DisputeReason {
  PAYMENT_NOT_RECEIVED = 'PAYMENT_NOT_RECEIVED',
  PAYMENT_INCORRECT_AMOUNT = 'PAYMENT_INCORRECT_AMOUNT',
  PAYMENT_DELAYED_BEYOND_TERMS = 'PAYMENT_DELAYED_BEYOND_TERMS',
  PAYOUT_MARKED_BUT_NOT_RECEIVED = 'PAYOUT_MARKED_BUT_NOT_RECEIVED',
  POST_EDITED_AFTER_APPROVAL = 'POST_EDITED_AFTER_APPROVAL',
  POST_REMOVED = 'POST_REMOVED',
  POST_QUALITY_BELOW_STANDARD = 'POST_QUALITY_BELOW_STANDARD',
  POST_WRONG_PLATFORM = 'POST_WRONG_PLATFORM',
  POST_MISSING_REQUIRED_ELEMENTS = 'POST_MISSING_REQUIRED_ELEMENTS',
  POST_DELETED_AFTER_PAYMENT = 'POST_DELETED_AFTER_PAYMENT',
  POST_EDITED_AFTER_PAYMENT = 'POST_EDITED_AFTER_PAYMENT',
  DISCLOSURE_REMOVED = 'DISCLOSURE_REMOVED',
  COMPETITOR_CONTENT_ADDED = 'COMPETITOR_CONTENT_ADDED',
  TERMS_VIOLATED_AFTER_PAYMENT = 'TERMS_VIOLATED_AFTER_PAYMENT',
}

export enum DisputeResolution {
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_ADJUSTED = 'PAYMENT_ADJUSTED',
  PAYMENT_DENIED = 'PAYMENT_DENIED',
  SUBMISSION_REVOKED = 'SUBMISSION_REVOKED',
  RESUBMISSION_REQUIRED = 'RESUBMISSION_REQUIRED',
  CONTENT_CORRECTION_REQUIRED = 'CONTENT_CORRECTION_REQUIRED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  NO_ACTION = 'NO_ACTION',
  MUTUAL_AGREEMENT = 'MUTUAL_AGREEMENT',
  DISMISSED = 'DISMISSED',
}

export enum DisputeMessageType {
  COMMENT = 'COMMENT',
  EVIDENCE = 'EVIDENCE',
  INTERNAL_NOTE = 'INTERNAL_NOTE',
  SYSTEM = 'SYSTEM',
  RESOLUTION_PROPOSAL = 'RESOLUTION_PROPOSAL',
}

export enum EvidenceType {
  SCREENSHOT = 'SCREENSHOT',
  LINK = 'LINK',
  DOCUMENT = 'DOCUMENT',
  OTHER = 'OTHER',
}
