import type {
  BountyListParams,
  MySubmissionsParams,
  SubmissionReviewListParams,
  AdminUserListParams,
  AdminBrandListParams,
  AuditLogListParams,
  AdminRecentErrorsParams,
  DisputeListParams,
  AdminDisputeListParams,
  HunterListParams,
  WalletTransactionListParams,
  WithdrawalListParams,
  AdminWalletListParams,
  AdminWithdrawalListParams,
  NotificationListParams,
  ConversationListParams,
  BrandListParams,
} from '@social-bounty/shared';

export const queryKeys = {
  bounties: {
    all: ['bounties'] as const,
    lists: () => [...queryKeys.bounties.all, 'list'] as const,
    list: (filters: BountyListParams) => [...queryKeys.bounties.lists(), filters] as const,
    details: () => [...queryKeys.bounties.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bounties.details(), id] as const,
  },
  submissions: {
    all: ['submissions'] as const,
    mine: (filters: MySubmissionsParams) => [...queryKeys.submissions.all, 'mine', filters] as const,
    forBounty: (bountyId: string, filters: SubmissionReviewListParams) =>
      [...queryKeys.submissions.all, 'forBounty', bountyId, filters] as const,
    detail: (id: string) => [...queryKeys.submissions.all, 'detail', id] as const,
    reviewQueue: (filters: Record<string, unknown>) => [...queryKeys.submissions.all, 'reviewQueue', filters] as const,
    myEarnings: () => [...queryKeys.submissions.all, 'myEarnings'] as const,
  },
  brands: {
    all: ['brands'] as const,
    detail: (id: string) => [...queryKeys.brands.all, 'detail', id] as const,
    members: (id: string) => [...queryKeys.brands.all, id, 'members'] as const,
    mine: () => [...queryKeys.brands.all, 'mine'] as const,
    publicList: (filters: BrandListParams) => [...queryKeys.brands.all, 'publicList', filters] as const,
    publicProfile: (idOrHandle: string) => [...queryKeys.brands.all, 'publicProfile', idOrHandle] as const,
    kybDocuments: (id: string) => [...queryKeys.brands.all, id, 'kyb', 'documents'] as const,
  },
  admin: {
    users: (filters: AdminUserListParams) => ['admin', 'users', filters] as const,
    userDetail: (id: string) => ['admin', 'users', id] as const,
    brands: (filters: AdminBrandListParams) => ['admin', 'brands', filters] as const,
    brandDetail: (id: string) => ['admin', 'brands', id] as const,
    auditLogs: (filters: AuditLogListParams) => ['admin', 'audit-logs', filters] as const,
    auditLogDetail: (id: string) => ['admin', 'audit-logs', id] as const,
    dashboard: ['admin', 'dashboard'] as const,
    systemHealth: ['admin', 'system-health'] as const,
    recentErrors: (filters: AdminRecentErrorsParams) => ['admin', 'recent-errors', filters] as const,
    settings: ['admin', 'settings'] as const,
  },
  disputes: {
    all: ['disputes'] as const,
    mine: (params: DisputeListParams) => [...queryKeys.disputes.all, 'mine', params] as const,
    forBrand: (params: DisputeListParams) => [...queryKeys.disputes.all, 'forBrand', params] as const,
    detail: (id: string) => [...queryKeys.disputes.all, 'detail', id] as const,
    adminList: (params: AdminDisputeListParams) => [...queryKeys.disputes.all, 'adminList', params] as const,
    stats: () => [...queryKeys.disputes.all, 'stats'] as const,
  },
  business: {
    dashboard: ['business', 'dashboard'] as const,
  },
  user: {
    me: ['user', 'me'] as const,
    socialLinks: ['user', 'social-links'] as const,
  },
  hunters: {
    all: ['hunters'] as const,
    lists: () => [...queryKeys.hunters.all, 'list'] as const,
    list: (filters: HunterListParams) => [...queryKeys.hunters.lists(), filters] as const,
    details: () => [...queryKeys.hunters.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.hunters.details(), id] as const,
  },
  wallet: {
    all: ['wallet'] as const,
    dashboard: () => [...queryKeys.wallet.all, 'dashboard'] as const,
    ledgerSnapshot: () => [...queryKeys.wallet.all, 'ledger-snapshot'] as const,
    transactions: (params: WalletTransactionListParams) => [...queryKeys.wallet.all, 'transactions', params] as const,
    withdrawals: (params: WithdrawalListParams) => [...queryKeys.wallet.all, 'withdrawals', params] as const,
    adminLists: () => [...queryKeys.wallet.all, 'admin', 'list'] as const,
    adminList: (params: AdminWalletListParams) => [...queryKeys.wallet.adminLists(), params] as const,
    adminDetail: (userId: string) => [...queryKeys.wallet.all, 'admin', 'detail', userId] as const,
    adminWithdrawals: (params: AdminWithdrawalListParams) => [...queryKeys.wallet.all, 'admin', 'withdrawals', params] as const,
  },
  bountyAccess: {
    myApplication: (bountyId: string) => ['bounty-access', 'my-application', bountyId] as const,
    applications: (bountyId: string, params?: Record<string, unknown>) =>
      ['bounty-access', 'applications', bountyId, params] as const,
    invitations: (bountyId: string) => ['bounty-access', 'invitations', bountyId] as const,
    myInvitations: () => ['bounty-access', 'my-invitations'] as const,
  },
  socialHandles: {
    mine: () => ['social-handles', 'mine'] as const,
    forUser: (userId: string) => ['social-handles', 'user', userId] as const,
  },
  inbox: {
    all: ['inbox'] as const,
    unreadCount: () => [...queryKeys.inbox.all, 'unread-count'] as const,
    notificationsAll: () => [...queryKeys.inbox.all, 'notifications'] as const,
    notifications: (params: NotificationListParams) => [...queryKeys.inbox.notificationsAll(), params] as const,
    conversationsAll: () => [...queryKeys.inbox.all, 'conversations'] as const,
    conversations: (params: ConversationListParams) => [...queryKeys.inbox.conversationsAll(), params] as const,
    conversationDetail: (id: string) => [...queryKeys.inbox.all, 'conversations', id] as const,
  },
};
